apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-app-lets-encrypt-cron
spec:
  schedule: "0 23 */7 * *"  # Every 7 days at 11PM
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.lets_encrypt.service_account_name }}
          automountServiceAccountToken: true
          containers:
          - image: 88lexd/lets-encrypt-cron:latest
            imagePullPolicy: Always
            name: todo-app-lets-encrypt-cron
            command: ["python3"]
            args: ["/app/main.py", "--cluster-config"]
            env:
            - name: TZ
              value: {{ .Values.time_zone }}
            - name: LE_ACCOUNT_KEY_NAME
              value: {{ .Values.lets_encrypt.account_key_secret_name }}
            - name: LE_PRIVATE_KEY_NAME
              value: {{ .Values.lets_encrypt.pivate_key_secret_name }}
            - name: LE_CSR_CONFIGMAP_NAME
              value: {{ .Values.lets_encrypt.csr_configmap_name }}
            - name: LE_TLS_SECRET_NAME
              value: {{ .Values.ingress_tls_secret_name }}
            - name: INGRESS_URL
              value: {{ .Values.ingress_url }}
            volumeMounts:
            - name: todo-app-volume
              mountPath: "/var/www/html/.well-known/acme-challenge"
          volumes:
          - name: todo-app-volume
            persistentVolumeClaim:
              claimName: todo-app-pvc
