---
time_zone: Australia/Sydney

number_of_replicas: 1
container_image: henrydinh/todo-app
# TODO: No longer using AWS CodeDeploy.
# Need to find an alternate solution to get tag from GitHub release for automated deployment
# container_image_tag: _VERSION_TAG_FROM_CI_
container_image_tag: 0.4
ingress_url: todo.henrydinh.net

