---
time_zone: Australia/Sydney

number_of_replicas: 1
container_image: henrydinh/todo-app
container_image_tag: _VERSION_TAG_FROM_CI_
ingress_url: todo.henrydinh.net
ingress_tls_secret_name: todo.henrydinh.net.tls

lets_encrypt:
  service_account_name: svc-todo-app-tls-secret-handler
  # These 2 secrets are created by Ansible
  account_key_secret_name: todo-henrydinh-net-account-key
  pivate_key_secret_name: todo-henrydinh-net-private-key
  # Details below is used by openssl to generate a CSR.
  csr_configmap_name: todo-henrydinh-net-csr-details-config
