---
time_zone: Australia/Sydney

number_of_replicas: 1
container_image: henrydinh/todo-app:0.1
ingress_url: henry.lexdsolutions.com
ingress_tls_secret_name: henry.lexdsolutions.com.tls

lets_encrypt:
  service_account_name: svc-todo-app-tls-secret-handler
  # These 2 secrets are created by Ansible
  account_key_secret_name: todo-app-account-key
  pivate_key_secret_name: todo-app-private-key
  # Details below is used by openssl to generate a CSR.
  csr_configmap_name: todo-app-csr-details-config