# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub

on:
  create:
    tags:
      - "[0-9]+.[0-9]+"  # Tag must be like 0.1, 1.0 etc.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Create version.txt
        run: echo '${{ github.event.ref }}' > ./version.txt

      - name: Create the .env-cmdrc.json from secret
        run: echo '${{ secrets.ENV_CMDRC }}' > ./.env-cmdrc.json

      - name: List all the files in the directory for next step
        run: ls -la ./

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/todo-app:${{ github.event.ref }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      #No longer running on AWS
      # - name: zip k8s-helm directory
      #   run: |
      #     cd ./k8s-helm/
      #     sed -i "s/_VERSION_TAG_FROM_CI_/${{ github.event.ref }}/g" values.yaml
      #     zip -r henry_todo_app.zip .

      # - name: Custom docker container action to push object to S3
      #   uses: ./.github/actions/push-object-to-s3
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_S3_ACCESS_KEY }}
      #     aws_secret_access_key: ${{ secrets.AWS_S3_SECRET_KEY }}
      #     aws_region: ap-southeast-2
      #     aws_s3_bucket_name: lexd-solutions-codedeploy
      #     source_file: ./k8s-helm/henry_todo_app.zip
      #     destination_path: /
      #     destination_file_name: henry_todo_app.zip
